### PR TITLE
send any responses that arent a tag's content in a reply instead of a regular message

### LINKED ISSUE #105: R.Danny should reply on tag create/edit/etc. to the demand message
Hi,

Actually, the bot confirms a create/update/... but it can be confusing if 2 users are on it during the same time.

e.g. https://discord.com/channels/172018499005317120/172254696101249024/829064159429787648

Is it possible to make it really responding on the demand message, please?

### PR DESCRIPTION
**Pull request by Rstar284**
Fixes #105

### CODE REVIEW

**Comment by Rapptz** [comment]
I don't like replying to everything, it's unnecessary noise.

**Comment by Lcfvs** [comment]
@Rapptz I don't share you opinion on tag operations, since several users can do something on a tag at a same time.

It can be confusing... and, imho, it isn't invasive ping, since a reaction is expected by the user editing a tag.

Do you have any counter-arguments? :)

If it remains like that, an history about the why can be friendly/useful.

**Comment by Rapptz** [comment]
As I mentioned, replies take up unnecessary noise. Multiple reply blocks means less messages are visible and it's distracting. If every bot interaction used a reply then this noise extrapolates everywhere.

**Comment by Lcfvs** [comment]
Maybe a way to add something like a flag to **ask** a reply instead? to avoid it by default, e.g. `?tag -r edit ....`

**Pull request closed without merging**
