### PR TITLE
More cards support in `?g`

### PR DESCRIPTION
**Pull request by PapyrusThePlant**
The translation card needed a new user-agent to be received, and as it changed the entire DOM, the parsing of existing cards has been adjusted.
I also added the parsing of timeline cards (e.g `python release date`) and quick search (e.g `flag of nepal`)

### CODE REVIEW

**Comment by Rapptz** [comment]
I can't get translation cards to show up and this broke some earlier cases like `?g ps2 emulator`.

**Comment by Rapptz** [comment]
Definition card is broken:

**Comment by PapyrusThePlant** [comment]
The translation card should show up now for your query `hello in spanish`, but note that it will not show up for some queries, e.g `translate in german hello my name is papyrus`.
The calculator card is displayed like before.
The card for `ps2 emulator` is now properly parsed.

I not know what to say about the definition card, as I said yesterday, it's fine on my end, maybe you're receiving a different DOM than me for this specific card :+1:
capture

**Comment by PapyrusThePlant** [comment]
Irrelevant now that you're rewriting R,Danny and making it all pretty in the inside.

**Pull request closed without merging**
